name: Deploy Docs to AWS

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via AWS CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name manush-e-docs \
            --deployment-group-name manush-e-docs \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
